# Shell variables
# Generated by 'wal'
wallpaper='/home/goddess/.config/images/goddess-purple.png'

# Special
background='#040705'
foreground='#dee0f6'
cursor='#dee0f6'

# Colors
color0='#040705'
color1='#659B9B'
color2='#699BCC'
color3='#A2B7CE'
color4='#9D9DEE'
color5='#B2ABFD'
color6='#C5B2FE'
color7='#dee0f6'
color8='#9b9cac'
color9='#659B9B'
color10='#699BCC'
color11='#A2B7CE'
color12='#9D9DEE'
color13='#B2ABFD'
color14='#C5B2FE'
color15='#dee0f6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
