--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/goddess/.config/images/goddess-purple.png"

-- Special
background="#040705"
foreground="#dee0f6"
cursor="#dee0f6"

-- Colors
color0="#040705"
color1="#659B9B"
color2="#699BCC"
color3="#A2B7CE"
color4="#9D9DEE"
color5="#B2ABFD"
color6="#C5B2FE"
color7="#dee0f6"
color8="#9b9cac"
color9="#659B9B"
color10="#699BCC"
color11="#A2B7CE"
color12="#9D9DEE"
color13="#B2ABFD"
color14="#C5B2FE"
color15="#dee0f6"
